# Generated by Django 5.0.6 on 2024-07-07 21:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Genesis", "Genesis"),
                            ("Exodus", "Exodus"),
                            ("Leviticus", "Leviticus"),
                            ("Numbers", "Numbers"),
                            ("Deuteronomy", "Deuteronomy"),
                            ("Joshua", "Joshua"),
                            ("Judges", "Judges"),
                            ("Ruth", "Ruth"),
                            ("1 Samuel", "1 Samuel"),
                            ("2 Samuel", "2 Samuel"),
                            ("1 Kings", "1 Kings"),
                            ("2 Kings", "2 Kings"),
                            ("1 Chronicles", "1 Chronicles"),
                            ("2 Chronicles", "2 Chronicles"),
                            ("Ezra", "Ezra"),
                            ("Nehemiah", "Nehemiah"),
                            ("Esther", "Esther"),
                            ("Job", "Job"),
                            ("Psalms", "Psalms"),
                            ("Proverbs", "Proverbs"),
                            ("Ecclesiastes", "Ecclesiastes"),
                            ("Song of Solomon", "Song of Solomon"),
                            ("Isaiah", "Isaiah"),
                            ("Jeremiah", "Jeremiah"),
                            ("Lamentations", "Lamentations"),
                            ("Ezekiel", "Ezekiel"),
                            ("Daniel", "Daniel"),
                            ("Hosea", "Hosea"),
                            ("Joel", "Joel"),
                            ("Amos", "Amos"),
                            ("Obadiah", "Obadiah"),
                            ("Jonah", "Jonah"),
                            ("Micah", "Micah"),
                            ("Nahum", "Nahum"),
                            ("Habakkuk", "Habakkuk"),
                            ("Zephaniah", "Zephaniah"),
                            ("Haggai", "Haggai"),
                            ("Zechariah", "Zechariah"),
                            ("Malachi", "Malachi"),
                            ("Matthew", "Matthew"),
                            ("Mark", "Mark"),
                            ("Luke", "Luke"),
                            ("John", "John"),
                            ("Acts", "Acts"),
                            ("Romans", "Romans"),
                            ("1 Corinthians", "1 Corinthians"),
                            ("2 Corinthians", "2 Corinthians"),
                            ("Galatians", "Galatians"),
                            ("Ephesians", "Ephesians"),
                            ("Philippians", "Philippians"),
                            ("Colossians", "Colossians"),
                            ("1 Thessalonians", "1 Thessalonians"),
                            ("2 Thessalonians", "2 Thessalonians"),
                            ("1 Timothy", "1 Timothy"),
                            ("2 Timothy", "2 Timothy"),
                            ("Titus", "Titus"),
                            ("Philemon", "Philemon"),
                            ("Hebrews", "Hebrews"),
                            ("James", "James"),
                            ("1 Peter", "1 Peter"),
                            ("2 Peter", "2 Peter"),
                            ("1 John", "1 John"),
                            ("2 John", "2 John"),
                            ("3 John", "3 John"),
                            ("Jude", "Jude"),
                            ("Revelation", "Revelation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verses_per_day",
                    models.SmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                ("days_of_review", models.SmallIntegerField(default=100)),
                (
                    "translation",
                    models.CharField(
                        choices=[
                            ("ESV", "English Standard Version"),
                            ("KJV", "King James Version"),
                        ],
                        max_length=5,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=40)),
                (
                    "current_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="current_plan",
                        to="refinery_app.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="refinery_app.plan"
            ),
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.CharField(
                        choices=[
                            ("Genesis", "Genesis"),
                            ("Exodus", "Exodus"),
                            ("Leviticus", "Leviticus"),
                            ("Numbers", "Numbers"),
                            ("Deuteronomy", "Deuteronomy"),
                            ("Joshua", "Joshua"),
                            ("Judges", "Judges"),
                            ("Ruth", "Ruth"),
                            ("1 Samuel", "1 Samuel"),
                            ("2 Samuel", "2 Samuel"),
                            ("1 Kings", "1 Kings"),
                            ("2 Kings", "2 Kings"),
                            ("1 Chronicles", "1 Chronicles"),
                            ("2 Chronicles", "2 Chronicles"),
                            ("Ezra", "Ezra"),
                            ("Nehemiah", "Nehemiah"),
                            ("Esther", "Esther"),
                            ("Job", "Job"),
                            ("Psalms", "Psalms"),
                            ("Proverbs", "Proverbs"),
                            ("Ecclesiastes", "Ecclesiastes"),
                            ("Song of Solomon", "Song of Solomon"),
                            ("Isaiah", "Isaiah"),
                            ("Jeremiah", "Jeremiah"),
                            ("Lamentations", "Lamentations"),
                            ("Ezekiel", "Ezekiel"),
                            ("Daniel", "Daniel"),
                            ("Hosea", "Hosea"),
                            ("Joel", "Joel"),
                            ("Amos", "Amos"),
                            ("Obadiah", "Obadiah"),
                            ("Jonah", "Jonah"),
                            ("Micah", "Micah"),
                            ("Nahum", "Nahum"),
                            ("Habakkuk", "Habakkuk"),
                            ("Zephaniah", "Zephaniah"),
                            ("Haggai", "Haggai"),
                            ("Zechariah", "Zechariah"),
                            ("Malachi", "Malachi"),
                            ("Matthew", "Matthew"),
                            ("Mark", "Mark"),
                            ("Luke", "Luke"),
                            ("John", "John"),
                            ("Acts", "Acts"),
                            ("Romans", "Romans"),
                            ("1 Corinthians", "1 Corinthians"),
                            ("2 Corinthians", "2 Corinthians"),
                            ("Galatians", "Galatians"),
                            ("Ephesians", "Ephesians"),
                            ("Philippians", "Philippians"),
                            ("Colossians", "Colossians"),
                            ("1 Thessalonians", "1 Thessalonians"),
                            ("2 Thessalonians", "2 Thessalonians"),
                            ("1 Timothy", "1 Timothy"),
                            ("2 Timothy", "2 Timothy"),
                            ("Titus", "Titus"),
                            ("Philemon", "Philemon"),
                            ("Hebrews", "Hebrews"),
                            ("James", "James"),
                            ("1 Peter", "1 Peter"),
                            ("2 Peter", "2 Peter"),
                            ("1 John", "1 John"),
                            ("2 John", "2 John"),
                            ("3 John", "3 John"),
                            ("Jude", "Jude"),
                            ("Revelation", "Revelation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("chapter", models.SmallIntegerField()),
                ("verse_number", models.SmallIntegerField()),
                ("days_reviewed", models.SmallIntegerField(default=1)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="refinery_app.plan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="current_verse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="current_plan",
                to="refinery_app.verse",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("api_key__isnull", False), ("translation", "ESV")),
                    models.Q(("translation", "ESV"), _negated=True),
                    _connector="OR",
                ),
                name="require_api_key_for_esv",
            ),
        ),
    ]
