# Generated by Django 5.0.6 on 2024-07-08 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refinery_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="current_verse",
            new_name="current_stop",
        ),
        migrations.AddField(
            model_name="plan",
            name="previous_stop",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="_current_plan",
                to="refinery_app.verse",
            ),
            preserve_default=False,
        ),
    ]
