# Generated by Django 5.0.6 on 2024-07-08 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refinery_app", "0002_rename_current_verse_plan_current_stop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="current_book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="current_plan",
                to="refinery_app.book",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="current_stop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="current_plan",
                to="refinery_app.verse",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="previous_stop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="_current_plan",
                to="refinery_app.verse",
            ),
        ),
    ]
