# Generated by Django 5.0.6 on 2024-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "refinery_app",
            "0003_alter_plan_current_book_alter_plan_current_stop_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plan",
            name="require_api_key_for_esv",
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("api_key", ""), _negated=True),
                    models.Q(("translation", "ESV"), _negated=True),
                    _connector="OR",
                ),
                name="require_api_key_for_esv",
            ),
        ),
    ]
